// tslint:disable:max-line-length

/**
 * Well known error codes
 */
export enum ErrorCode {

  // General errors
  UNKNOWN = 'UNKNOWN',
  CONNECTIVITY_PROBLEMS = 'CONNECTIVITY_PROBLEMS',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  TIMEOUT = 'TIMEOUT',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  NOT_SUPPORTED = 'NOT_SUPPORTED',
  CANCELED = 'CANCELED',
  FILE_SIZE_EXCEEDED = 'FILE_SIZE_EXCEEDED',
  TOO_MANY_RESULTS = 'TOO_MANY_RESULTS',
  INVALID_ADDRESS = 'INVALID_ADDRESS',
}
