language: node_js

dist: xenial

node_js:
  - '10'

cache:
  npm

install:
  - npm install

script:
  - npm run build

before_deploy:
  - pip install --user --upgrade awscli

notifications:
  email:
    on_failure: change

deploy:
  - provider: script
    skip_cleanup: true
    script: bash internals/scripts/deploy-s3.sh build
    on:
      repo: ${TRAVIS_REPO_SLUG}
      branch: master
