language: node_js

dist: xenial

node_js:
  - '10'

cache:
  npm

install:
  - npm install

script:
  - npm run build

before_deploy:
  - npm run dist:prepare-archives
  - pip install --user --upgrade awscli

notifications:
  email:
    on_failure: change

deploy:
  - provider: script
    skip_cleanup: true
    script: bash internals/scripts/deploy-s3.sh build
    on:
      repo: ${TRAVIS_REPO_SLUG}
      tags: true
      condition: $TRAVIS_TAG = release
  - provider: releases
    api_key:
      secure: hZMjAxB+1JWwO/GlaKEu2lZQbedgOJw0GCyZy4O48jFEnrua4MwlBNbS+9dwsqFOO3EtIKQ1jXQEdhXryr3WHEIT63f4AXO5j0FTgWSQWVPt4y4g8L01pdnu9Ff+HmypKKoAadkUUy5vGBDoizP5sq6tZB+bkmYJdlRI2ZXVCyT3DpS3nyRIKN77S3Wcnc0cl60VX91WhNfbC2HOXWI5CQUYWVOEOQ21ynhOXpZs5XQZgnQofjy40xqEFiZOPp+yQpe/NaR3n7nXGooY+ItPITAPrBbWwWdaebIR/oMVhXNBp9E40pti04BZsl+xyRHQsVyCFOSN/DUxpSUbYgi9cY94MF2TxYT58mjYMlXtLsOUenf8irZLqpdvv2Z4JDeJd6ja3ENwoKv1H8pOyDk116dhfPlbRcrSIQWFWw9y3AK8hV2cnCKaAgWahGHMumyzUK7PqClTF3r7jb+XOJOPi8Mn2Ki/EllByt+cGSbETDj2/8uUBhga0IUPvemOE/rd4XehrTj0oijs2ftvTIP8Dbq6UB5IusNLcAaCRoTNaZVlczy6xV4LkpGZJXhHnBD+hvOdzi5J74Qi5L9j9todMfFV6YhbyLFarapMwC9KHVhchddr+wma4rLUis2NsBnjDTUpAba5evGHzqtEe62qIOJfRw+1maAEz1pML+5w2oU=
    file: dist/*.{tar.gz}
    file_glob: true
    skip_cleanup: true
    overwrite: true
    draft: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      tags: true